mongo:
  username: "![D3p51JdEUZ7mTO2eDd9USw==]"
  password: "![Rb10WCuoljyt9z3fsluy0PnJ3J2Zpl6L]"
  database: "pocs"
  collection: "notifications"
anypoint:
  mq:
    client_id: "![WPHC7EjAcb7aKyq0eya3H1FLw15px5V1P7sq42OMBpxGzgg8MK4wzw==]"
    client_secret: "![1WkPSVmRTsX+b5FtYAPfYoJg/PzrI/pho8PibwOigkiiXPbC2NnwSg==]"
    exchange: "notifications"