mongo:
  username: "![D3p51JdEUZ7mTO2eDd9USw==]"
  password: "![Rb10WCuoljyt9z3fsluy0PnJ3J2Zpl6L]"
  database: "pocs"
  collection: "demo-accounts"
anypoint:
  mq:
    client_id: "![f6tAsXW73ebSmQq2YkzBftrcJVAFF6pYMabJD4rZ16tM6ApyhXRSoA==]"
    client_secret: "![bbmbX7cNkti+tp7t+A2aD4I5M+tny9mCufjtnE1xA7Oqn4c7GGtF0Q==]"
    queue: "sfdc-account-sync"
sfdc:
  token: "![Dp8K9Jbmt+mToTU/k02VfCVwQcnDAJtNoR3iWVUcK80=]"
  username: "![PWD+02kJEroP00CYz3aMttVppeigtx9M]"
  password: "![AlTHFOK2JcwDH4ulOJxvy5id5A/LqidNEHXcdr5kZ3w=]"